# Домашнее задание №6
## Библиотека numpy
---
**Выполнила:** Халфина Айсылу Зуфаровна

**Группа:** НПМбд-02-19

---

In [2]:
import numpy as np

1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [3]:
np.linspace(-1.3, 2.5, 64)

array([-1.3       , -1.23968254, -1.17936508, -1.11904762, -1.05873016,
       -0.9984127 , -0.93809524, -0.87777778, -0.81746032, -0.75714286,
       -0.6968254 , -0.63650794, -0.57619048, -0.51587302, -0.45555556,
       -0.3952381 , -0.33492063, -0.27460317, -0.21428571, -0.15396825,
       -0.09365079, -0.03333333,  0.02698413,  0.08730159,  0.14761905,
        0.20793651,  0.26825397,  0.32857143,  0.38888889,  0.44920635,
        0.50952381,  0.56984127,  0.63015873,  0.69047619,  0.75079365,
        0.81111111,  0.87142857,  0.93174603,  0.99206349,  1.05238095,
        1.11269841,  1.17301587,  1.23333333,  1.29365079,  1.35396825,
        1.41428571,  1.47460317,  1.53492063,  1.5952381 ,  1.65555556,
        1.71587302,  1.77619048,  1.83650794,  1.8968254 ,  1.95714286,
        2.01746032,  2.07777778,  2.13809524,  2.1984127 ,  2.25873016,
        2.31904762,  2.37936508,  2.43968254,  2.5       ])

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [4]:
n = 5
np.tile([1, 2, 3], n)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

3.	Создайте массив первых 10 нечетных целых чисел.

In [5]:
np.arange(1, 20, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [6]:
zeros = np.zeros(100).reshape(10,10)
frame = np.pad(zeros, pad_width=1, constant_values=1)
frame

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [7]:
board = np.ones(64).reshape(8,8)
board[1::2,::2] = 0
board[::2,1::2] = 0
board

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [8]:
def create_matrix(n):
    A = np.zeros((n, n))
    for i in range(n):
        A[i] = np.arange(i, i + n)
    return A
create_matrix(6)

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 2.,  3.,  4.,  5.,  6.,  7.],
       [ 3.,  4.,  5.,  6.,  7.,  8.],
       [ 4.,  5.,  6.,  7.,  8.,  9.],
       [ 5.,  6.,  7.,  8.,  9., 10.]])

7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [9]:
Vector_1 = np.arange(1, 5)
Vector_2 = np.arange(5, 9)
Matrix_1 = np.arange(1,21).reshape(4,5)
Matrix_2 = np.arange(15,0,-1).reshape(5,3)
print('Vector_1 x Vector_2 =', np.dot(Vector_1, Vector_2))
print('Vector_1 x Matrix_1 =', np.dot(Vector_1, Matrix_1))
print('Matrix_1 x Matrix_2 =', np.dot(Matrix_1, Matrix_2))

Vector_1 x Vector_2 = 70
Vector_1 x Matrix_1 = [110 120 130 140 150]
Matrix_1 x Matrix_2 = [[105  90  75]
 [330 290 250]
 [555 490 425]
 [780 690 600]]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [10]:
interval = np.arange(0,1,0.05)
cos = np.cos(interval[::])
sin = np.sin(interval[::])
result = np.vstack((cos,sin))
result

array([[1.        , 0.99875026, 0.99500417, 0.98877108, 0.98006658,
        0.96891242, 0.95533649, 0.93937271, 0.92106099, 0.9004471 ,
        0.87758256, 0.85252452, 0.82533561, 0.7960838 , 0.76484219,
        0.73168887, 0.69670671, 0.65998315, 0.62160997, 0.58168309],
       [0.        , 0.04997917, 0.09983342, 0.14943813, 0.19866933,
        0.24740396, 0.29552021, 0.34289781, 0.38941834, 0.43496553,
        0.47942554, 0.52268723, 0.56464247, 0.60518641, 0.64421769,
        0.68163876, 0.71735609, 0.75128041, 0.78332691, 0.8134155 ]])

9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [11]:
Matrix_A = 4 * np.random.rand(3,5) - 1
Matrix_A

array([[ 0.79808635,  0.19753513,  2.12108995,  1.7393882 ,  0.76806385],
       [-0.43858801,  2.08271392,  1.99759029,  2.97053607,  0.69564723],
       [ 1.10693478,  0.15670841,  2.27148291,  0.46073085,  0.02945812]])

10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [12]:
print('Сумма всех элементов:', np.sum(Matrix_A))
print('Сумма внутри строк:', np.sum(Matrix_A, axis = 1))
print('Сумма внутри столбцов:', np.sum(Matrix_A, axis = 0))
print('Среднее значение строк:', np.mean(Matrix_A, axis = 1))
print('Дисперсия строк:', np.var(Matrix_A, axis = 1))
print('Стандартное отклонение строк:', np.sqrt(np.var(Matrix_A, axis = 1)))

Сумма всех элементов: 16.95737805503326
Сумма внутри строк: [5.62416349 7.3078995  4.02531506]
Сумма внутри столбцов: [1.46643313 2.43695746 6.39016316 5.17065511 1.4931692 ]
Среднее значение строк: [1.1248327  1.4615799  0.80506301]
Дисперсия строк: [0.49282699 1.42947085 0.67640103]
Стандартное отклонение строк: [0.70201637 1.1956048  0.82243604]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [13]:
(Matrix_A - np.array([np.mean(Matrix_A, axis = 1),]).T) / np.array([np.sqrt(np.var(Matrix_A, axis = 1)),]).T

array([[-0.46543977, -1.32090589,  1.41913678,  0.87541477, -0.50820588],
       [-1.5892943 ,  0.51951449,  0.44831736,  1.26208607, -0.64062361],
       [ 0.36704589, -0.78833438,  1.78302   , -0.41867349, -0.94305801]])

12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [14]:
Matrix_A[np.argsort(Matrix_A[:, 2])]

array([[-0.43858801,  2.08271392,  1.99759029,  2.97053607,  0.69564723],
       [ 0.79808635,  0.19753513,  2.12108995,  1.7393882 ,  0.76806385],
       [ 1.10693478,  0.15670841,  2.27148291,  0.46073085,  0.02945812]])

13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [15]:
a = np.random.randint(1, 10, size = (3,4))
Matrix_B = np.dot(a.T,a)
Matrix_C = np.dot(a,a.T)
print('B: ', Matrix_B)
print('C: ', Matrix_C)

# Обе матрицы кввадратные
# Размер матрицы B зависит от количества столбцов матрицы А, а размер матрицы C зависит от количества её строк

B:  [[42 29 53 33]
 [29 29 34 31]
 [53 34 98 58]
 [33 31 58 45]]
C:  [[ 51  30  67]
 [ 30  37  45]
 [ 67  45 126]]


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [16]:
print('B:', sum(np.diag(Matrix_B)))
print('C:', sum(np.diag(Matrix_C)))

B: 214
C: 214


15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [17]:
def get_det(matrix):
    if matrix.shape[0] != matrix.shape[1]:
        return 'не определён'
    return np.linalg.det(matrix)

Det_A = get_det(Matrix_A)
Det_B = get_det(Matrix_B)
Det_C = get_det(Matrix_C)
Rank_A = np.linalg.matrix_rank(Matrix_A)
Rank_B = np.linalg.matrix_rank(Matrix_B)
Rank_C = np.linalg.matrix_rank(Matrix_C)
Eig_B = np.linalg.eig(Matrix_B)
Eig_C = np.linalg.eig(Matrix_C)
print('Матрица А')
print('Детерминант: ', Det_A)
print('Ранг: ', Rank_A)
print('')
print('Матрица B')
print('Детерминант: ', Det_B)
print('Ранг: ', Rank_B)
print('Спектр: ', Eig_B)
print('')
print('Матрица C')
print('Детерминант: ', Det_C)
print('Ранг: ', Rank_C)
print('Спектр: ', Eig_C)

Матрица А
Детерминант:  не определён
Ранг:  3

Матрица B
Детерминант:  0.0
Ранг:  3
Спектр:  (array([1.84987402e+02, 1.07688500e-14, 1.04568697e+01, 1.85557286e+01]), array([[ 0.43291409,  0.42225914, -0.7403322 ,  0.29358278],
       [ 0.32550474, -0.61755399,  0.11815611,  0.70619605],
       [ 0.70066418, -0.34836379, -0.03549623, -0.62165296],
       [ 0.46443704,  0.5647716 ,  0.66082327,  0.16924506]]))

Матрица C
Детерминант:  35893.99999999996
Ранг:  3
Спектр:  (array([184.98740177,  10.45686966,  18.55572857]), array([[ 0.48042546,  0.85853988, -0.17916657],
       [ 0.34285796, -0.3718808 , -0.86264309],
       [ 0.8072421 , -0.35300702,  0.47301823]]))


16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять один из следующих с номером, сгенерированным случайным образом с помощью функции np.random.randint(10), в качестве seed для генератора случайных чисел взять номер своего студенческого билета.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        <td> 9) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        </tr>
</table>

In [18]:
np.random.seed(1032196007)
v = np.random.randint(10)
v

7

In [29]:
def f(y):
    return 1 / (y**2-2*y-8)

def rectangle(f, a, b, step):
    X = np.linspace(a, b, int((b - a) / step) + 1)
    return step * np.sum(f(X)[:len(X) - 1])

def trapezoid(f, a, b, step):
    X = np.linspace(a, b, int((b - a) / step) + 1)
    f = f(X)
    return step / 2 * (f[0] + 2 * np.sum(f[1 : len(X) - 1]) + f[-1])

def simpson(f, a, b, step):
    X = np.linspace(a, b, 2 * int((b - a) / step) + 1)
    N = len(X) - 1
    f = f(X)
    return step / 6 * (f[0] + 2 * np.sum(f[2 : N : 2])  + 4 * np.sum(f[1 : N : 2]) + f[N])

print('Метод прямоугольников:', rectangle(f, 2, 3, 0.00001))
print('Метод трапеций:', trapezoid(f, 2, 3, 0.001))
print('Метод Симпсона:', simpson(f, 2, 3, 0.01))

Метод прямоугольников: -0.152713219828879
Метод трапеций: -0.1527151327081912
Метод Симпсона: -0.15271512198228884


$\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy} = \int\limits_2^3 {\frac{{1}}{{(y-4)}{(y+2)}}dy} = \int\limits_2^3 {(\frac{{1}}{{6(y-4)}}-\frac{{1}}{{6(y+2)}})dy} = (\dfrac{\ln\left(\left|y-4\right|\right)}{6}-\dfrac{\ln\left(\left|y+2\right|\right)}{6})\Biggr|_{2}^{3} = -\dfrac{\ln\left(5\right)}{6}+\dfrac{\ln\left(4\right)}{6}-\dfrac{\ln\left(2\right)}{6} = \dfrac{\ln\left(2\right)-\ln\left(5\right)}{6} \approx$

$\approx − 0.1527151219790258$

Вывод: метод Симпсона даёт наиболее точный результат при наименьшем количестве шагов.